version: '3.8'

services:
  back:
    build: ./back
    volumes:
      - ./back:/back
      - /back/node_modules
    working_dir: /back
    ports:
      - 5900:5900
    env_file:
      - .env
    command: npm run start
    restart: always

  front:
    build: ./front
    volumes:
      - ./front:/front
      - /front/node_modules
      - /front/dist
    working_dir: /front
    ports:
      - 4173:4173
    env_file:
      - .env
    command: npm run preview
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./front/dist:/usr/share/nginx/html
    depends_on:
      - front
    restart: always